In [80]:
import pandas as pd
from sklearn.utils import resample
from sklearn.model_selection import train_test_split

In [81]:
datos_final = pd.read_csv("datos_final.csv").drop("Unnamed: 0", axis = 1)

In [82]:
datos_final.head()

,BP,Departamento,Hombres,Mujeres,Total Víctimas,Valor total cofinanciación ADR,Valor Contrapartida,Hectáreas,Vigencia,CADENA_PRODUCTIVA_ADR
0,6,CHOCO,30,5,0,250000000,513500000,100,2017,PLATANO
1,17,META,31,9,0,500000000,106600000,40,2017,CAFE
2,23,ANTIOQUIA,20,5,23,401373250,355140000,69,2017,PLATANO
3,23,ANTIOQUIA,20,5,23,401373250,355140000,69,2017,PLATANO
4,25,META,16,12,10,255000000,41570000,93,2017,CAUCHO

In [83]:
datos_final.columns

Index(['BP', 'Departamento', 'Hombres', 'Mujeres', 'Total Víctimas',
       'Valor total cofinanciación ADR', 'Valor Contrapartida', 'Hectáreas',
       'Vigencia', 'CADENA_PRODUCTIVA_ADR'],
      dtype='object')

In [84]:
datos_final.CADENA_PRODUCTIVA_ADR.value_counts()

PLATANO       31
CAFE          22
MARACUYA       9
TOMATE         9
AGUACATE       8
FRIJOL         4
MAIZ           4
COCO           3
CACAO          3
PAPA           2
TANGELO        2
PERA           2
ÑAME           1
CAUCHO         1
FRESA          1
MORA           1
GRANADILLA     1
MANGO          1
Name: CADENA_PRODUCTIVA_ADR, dtype: int64

In [85]:
# Separate input features and target
y = datos_final.CADENA_PRODUCTIVA_ADR
X = datos_final.drop('CADENA_PRODUCTIVA_ADR', axis=1)

In [86]:
# setting up testing and training sets
#X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.20, random_state=27)

In [87]:
# concatenate our training data back together
X = pd.concat([X, y], axis=1)

In [88]:
categories = datos_final.CADENA_PRODUCTIVA_ADR.unique()

In [89]:
categories

array(['PLATANO', 'CAFE', 'CAUCHO', 'TOMATE', 'MANGO', 'CACAO', 'ÑAME',
       'MORA', 'AGUACATE', 'GRANADILLA', 'TANGELO', 'PERA', 'MAIZ',
       'PAPA', 'FRIJOL', 'MARACUYA', 'FRESA', 'COCO'], dtype=object)

In [90]:
# separate minority and majority classes
"""not_fraud = X[X.Class==0]
fraud = X[X.Class==1]"""

classes = {}
for category in categories:
    classes.update({str(category):X[X.CADENA_PRODUCTIVA_ADR==category]})

In [91]:
classes

{'PLATANO':       BP        Departamento  Hombres  Mujeres  Total Víctimas  \
 0      6               CHOCO       30        5               0
 2     23           ANTIOQUIA       20        5              23
 3     23           ANTIOQUIA       20        5              23
 6     44               CHOCO       52       21              48
 7     44               CHOCO       52       21              48
 8     44               CHOCO       52       21              48
 19    77               CHOCO       55       17              12
 20    77               CHOCO       55       17              12
 27   100             CORDOBA       36       30              13
 28   101                META        4       43              17
 37   124             BOLIVAR      179       21              45
 41   132                META       87       61              62
 42   132                META       87       61              62
 45   136               CHOCO      115       12             118
 46   136               CHOCO      115       12             118
 47   140               CHOCO       96       28             105
 48   140               CHOCO       96       28             105
 50   143             CORDOBA       65       28              37
 57   150             BOLÍVAR       84       10              38
 59   156                META       54       33              43
 60   156                META       54       33              43
 64   163               CHOCO        2       38              31
 65   165               CHOCO       18       12              15
 66   165               CHOCO       18       12              15
 78   354             CORDOBA       59       20              15
 92   252  NORTE DE SANTANDER       46        8               8
 93   252  NORTE DE SANTANDER       46        8               8
 94   278  NORTE DE SANTANDER       32        7              27
 102  719             VICHADA      130       20              23
 103  719             VICHADA      130       20              23
 104  744              CALDAS       39        9               7

      Valor total cofinanciación ADR  Valor Contrapartida  Hectáreas  Vigencia  \
 0                         250000000            513500000        100      2017
 2                         401373250            355140000         69      2017
 3                         401373250            355140000         69      2017
 6                         346452142            524040000         73      2017
 7                         346452142            524040000         73      2017
 8                         346452142            524040000         73      2017
 19                        278014950            134900000         55      2017
 20                        278014950            134900000         55      2017
 27                        999993000            122760000         66      2017
 28                        390795000            346040371         47      2016
 37                       2000000000            575750000        200      2017
 41                       1476660080            489288000        148      2017
 42                       1476660080            489288000        148      2017
 45                        336281247            184327940         26      2017
 46                        336281247            184327940         26      2017
 47                        418498400            120116000        143      2017
 48                        418498400            120116000        143      2017
 50                       1000000000            314340000         93      2017
 57                        977966000            282000000         94      2018
 59                        906940020            264915000         87      2017
 60                        906940020            264915000         87      2017
 64                        729547396            334850000         80      2017
 65                        249869700            159600000         30      2017
 66                        249869700            159600000         30      2017
 78                        997569966            379200000         79      2019
 92                        373952000            307280000         54      2017
 93                        373952000            307280000         54      2017
 94                        345194000            128910000         39      2017
 102                      1713390566            724500000        150      2019
 103                      1713390566            724500000        150      2019
 104                       291926566            196880000         48      2019

     CADENA_PRODUCTIVA_ADR
 0                 PLATANO
 2                 PLATANO
 3                 PLATANO
 6                 PLATANO
 7                 PLATANO
 8                 PLATANO
 19                PLATANO
 20                PLATANO
 27                PLATANO
 28                PLATANO
 37                PLATANO
 41                PLATANO
 42                PLATANO
 45                PLATANO
 46                PLATANO
 47                PLATANO
 48                PLATANO
 50                PLATANO
 57                PLATANO
 59                PLATANO
 60                PLATANO
 64                PLATANO
 65                PLATANO
 66                PLATANO
 78                PLATANO
 92                PLATANO
 93                PLATANO
 94                PLATANO
 102               PLATANO
 103               PLATANO
 104               PLATANO  ,
 'CAFE':      BP Departamento  Hombres  Mujeres  Total Víctimas  \
 1    17         META       31        9               0
 5    31        CAUCA       40       11               6
 21   80       CALDAS       37       13               0
 22   80       CALDAS       37       13               0
 23   81       CALDAS       41        9              10
 24   81       CALDAS       41        9              10
 26   94       NARIÑO       31        9               9
 30  108        HUILA        0       27               1
 32  114        HUILA       27        8               4
 33  117        HUILA       31       10               5
 38  129        HUILA       49       21               9
 39  129        HUILA       49       21               9
 49  142        HUILA       43       10               9
 53  147       TOLIMA       19       11              15
 54  147       TOLIMA       19       11              15
 58  151        HUILA       38       17               5
 63  552        HUILA       36        9               1
 67  167   LA_GUAJIRA       13        6              17
 69  307        HUILA       47       13               6
 71  324       NARIÑO       41        5              14
 95  231        CAUCA      259      141              22
 96  231        CAUCA      259      141              22

     Valor total cofinanciación ADR  Valor Contrapartida  Hectáreas  Vigencia  \
 1                        500000000            106600000         40      2017
 5                        501204000             99735000         51      2017
 21                       500000000            130250000         50      2016
 22                       500000000            130250000         50      2016
 23                       500000000            130250000         50      2016
 24                       500000000            130250000         50      2016
 26                       434216599            139320000         40      2016
 30                       353046000            115290000         27      2017
 32                       362280400            105972405         70      2017
 33                       412121840             82612500         82      2017
 38                       232852000           1225999000        141      2017
 39                       232852000           1225999000        141      2017
 49                       375495000             78145000         80      2017
 53                       200000000            106200000         60      2017
 54                       200000000            106200000         60      2017
 58                       392075000             80075000         83      2017
 63                       320175000             56233000         68      2017
 67                       284477000             96780000         19      2017
 69                       500057000             95908000         90      2017
 71                       579035466            200205000         46      2018
 95                      2966390566            342479053          0      2019
 96                      2966390566            342479053          0      2019

    CADENA_PRODUCTIVA_ADR
 1                   CAFE
 5                   CAFE
 21                  CAFE
 22                  CAFE
 23                  CAFE
 24                  CAFE
 26                  CAFE
 30                  CAFE
 32                  CAFE
 33                  CAFE
 38                  CAFE
 39                  CAFE
 49                  CAFE
 53                  CAFE
 54                  CAFE
 58                  CAFE
 63                  CAFE
 67                  CAFE
 69                  CAFE
 71                  CAFE
 95                  CAFE
 96                  CAFE  ,
 'CAUCHO':    BP Departamento  Hombres  Mujeres  Total Víctimas  \
 4  25         META       16       12              10

    Valor total cofinanciación ADR  Valor Contrapartida  Hectáreas  Vigencia  \
 4                       255000000             41570000         93      2017

   CADENA_PRODUCTIVA_ADR
 4                CAUCHO  ,
 'TOMATE':      BP Departamento  Hombres  Mujeres  Total Víctimas  \
 9    48        CAUCA       17        3               9
 10   48        CAUCA       17        3               9
 11   48        CAUCA       17        3               9
 13   66        CAUCA       13        3              13
 14   66        CAUCA       13        3              13
 15   66        CAUCA       13        3              13
 16   66        CAUCA       13        3              13
 17   66        CAUCA       13        3              13
 36  123       NARIÑO       43       19              10

     Valor total cofinanciación ADR  Valor Contrapartida  Hectáreas  Vigencia  \
 9                        197000000             71010000          5      2016
 10                       197000000             71010000          5      2016
 11                       197000000             71010000          5      2016
 13                       410400000            189208102         51      2016
 14                       410400000            189208102         51      2016
 15                       410400000            189208102         51      2016
 16                       410400000            189208102         51      2016
 17                       410400000            189208102         51      2016
 36                      1380752000            430716000          6      2017

    CADENA_PRODUCTIVA_ADR
 9                 TOMATE
 10                TOMATE
 11                TOMATE
 13                TOMATE
 14                TOMATE
 15                TOMATE
 16                TOMATE
 17                TOMATE
 36                TOMATE  ,
 'MANGO':     BP Departamento  Hombres  Mujeres  Total Víctimas  \
 12  49    ATLANTICO      103       37              15

     Valor total cofinanciación ADR  Valor Contrapartida  Hectáreas  Vigencia  \
 12                      1505613100            350547400        140      2017

    CADENA_PRODUCTIVA_ADR
 12                 MANGO  ,
 'CACAO':      BP Departamento  Hombres  Mujeres  Total Víctimas  \
 18   68        CHOCO      180      120             241
 83  378      GUAINIA       87        3              36
 84  378      GUAINIA       87        3              36

     Valor total cofinanciación ADR  Valor Contrapartida  Hectáreas  Vigencia  \
 18                      1500000000           1632000000        300      2017
 83                       731834400            634457600        184      2017
 84                       731834400            634457600        184      2017

    CADENA_PRODUCTIVA_ADR
 18                 CACAO
 83                 CACAO
 84                 CACAO  ,
 'ÑAME':     BP Departamento  Hombres  Mujeres  Total Víctimas  \
 25  90    MAGDALENA      128       32              65

     Valor total cofinanciación ADR  Valor Contrapartida  Hectáreas  Vigencia  \
 25                      1500000000            336000000        160      2017

    CADENA_PRODUCTIVA_ADR
 25                  ÑAME  ,
 'MORA':      BP Departamento  Hombres  Mujeres  Total Víctimas  \
 29  102       NARIÑO       21       11               3

     Valor total cofinanciación ADR  Valor Contrapartida  Hectáreas  Vigencia  \
 29                       500000000            106272000         16      2016

    CADENA_PRODUCTIVA_ADR
 29                  MORA  ,
 'AGUACATE':       BP  Departamento  Hombres  Mujeres  Total Víctimas  \
 31   693        CALDAS      240       51             105
 34   118        CALDAS      121       35              75
 40   131  CUNDINAMARCA      121       49              23
 72   318        CALDAS      280       73             328
 73   318        CALDAS      280       73             328
 74   318        CALDAS      280       73             328
 76   183     ANTIOQUIA       14        6               4
 101  264        BOYACA      167       74              31

      Valor total cofinanciación ADR  Valor Contrapartida  Hectáreas  Vigencia  \
 31                       1499984371            166700718        291      2016
 34                       1972185600            422136000        156      2017
 40                       2479938287            912830408        170      2017
 72                        999522000            529500000        353      2017
 73                        999522000            529500000        353      2017
 74                        999522000            529500000        353      2017
 76                        530010000             71400000         20      2017
 101                      1598290566            678030000        241      2019

     CADENA_PRODUCTIVA_ADR
 31               AGUACATE
 34               AGUACATE
 40               AGUACATE
 72               AGUACATE
 73               AGUACATE
 74               AGUACATE
 76               AGUACATE
 101              AGUACATE  ,
 'GRANADILLA':      BP Departamento  Hombres  Mujeres  Total Víctimas  \
 35  119       NARIÑO       72       15              11

     Valor total cofinanciación ADR  Valor Contrapartida  Hectáreas  Vigencia  \
 35                       868027011            716662200          7      2016

    CADENA_PRODUCTIVA_ADR
 35            GRANADILLA  ,
 'TANGELO':      BP Departamento  Hombres  Mujeres  Total Víctimas  \
 43  133    SANTANDER       95       33               8
 44  133    SANTANDER       95       33               8

     Valor total cofinanciación ADR  Valor Contrapartida  Hectáreas  Vigencia  \
 43                      2000000000            391568000        128      2017
 44                      2000000000            391568000        128      2017

    CADENA_PRODUCTIVA_ADR
 43               TANGELO
 44               TANGELO  ,
 'PERA':      BP Departamento  Hombres  Mujeres  Total Víctimas  \
 51  144         META       62       30              44
 52  144         META       62       30              44

     Valor total cofinanciación ADR  Valor Contrapartida  Hectáreas  Vigencia  \
 51                       669701000            342855000         92      2017
 52                       669701000            342855000         92      2017

    CADENA_PRODUCTIVA_ADR
 51                  PERA
 52                  PERA  ,
 'MAIZ':      BP     Departamento  Hombres  Mujeres  Total Víctimas  \
 55  148          BOLIVAR      205        0             182
 61  157          BOLIVAR      133        0             123
 62  157          BOLIVAR      133        0             123
 68  168  VALLE DEL CAUCA      124       27               9

     Valor total cofinanciación ADR  Valor Contrapartida  Hectáreas  Vigencia  \
 55                      1979133000            445252000        820      2017
 61                      2143671000            296640000        119      2017
 62                      2143671000            296640000        119      2017
 68                      4510439997          18170032752       1501      2018

    CADENA_PRODUCTIVA_ADR
 55                  MAIZ
 61                  MAIZ
 62                  MAIZ
 68                  MAIZ  ,
 'PAPA':        BP  Departamento  Hombres  Mujeres  Total Víctimas  \
 56    149        BOYACA      278       69               0
 100  2085  CUNDINAMARCA      189       31               0

      Valor total cofinanciación ADR  Valor Contrapartida  Hectáreas  Vigencia  \
 56                       3618584000           1455284620        270      2017
 100                      3085065566           1478103000          4      2019

     CADENA_PRODUCTIVA_ADR
 56                   PAPA
 100                  PAPA  ,
 'FRIJOL':      BP        Departamento  Hombres  Mujeres  Total Víctimas  \
 70  311        CUNDINAMARCA       71       22              11
 85  382               CESAR       33       15              20
 86  382               CESAR       33       15              20
 87  285  NORTE DE SANTANDER       66        3              10

     Valor total cofinanciación ADR  Valor Contrapartida  Hectáreas  Vigencia  \
 70                       566214100            262245320         93      2017
 85                       731059536            250892720         48      2019
 86                       731059536            250892720         48      2019
 87                       494040000            421500000         69      2017

    CADENA_PRODUCTIVA_ADR
 70                FRIJOL
 85                FRIJOL
 86                FRIJOL
 87                FRIJOL  ,
 'MARACUYA':      BP        Departamento  Hombres  Mujeres  Total Víctimas  \
 75  346              ARAUCA       16        9              14
 79  371              NARIÑO       21       16              23
 80  371              NARIÑO       21       16              23
 81  371              NARIÑO       21       16              23
 82  371              NARIÑO       21       16              23
 88  276  NORTE DE SANTANDER       58       11              12
 89  276  NORTE DE SANTANDER       58       11              12
 90  276  NORTE DE SANTANDER       58       11              12
 91  276  NORTE DE SANTANDER       58       11              12

     Valor total cofinanciación ADR  Valor Contrapartida  Hectáreas  Vigencia  \
 75                       375523000            185194000         25      2018
 79                       533630234            198360000         37      2018
 80                       533630234            198360000         37      2018
 81                       533630234            198360000         37      2018
 82                       533630234            198360000         37      2018
 88                       715210000            144491000        340      2018
 89                       715210000            144491000        340      2018
 90                       715210000            144491000        340      2018
 91                       715210000            144491000        340      2018

    CADENA_PRODUCTIVA_ADR
 75              MARACUYA
 79              MARACUYA
 80              MARACUYA
 81              MARACUYA
 82              MARACUYA
 88              MARACUYA
 89              MARACUYA
 90              MARACUYA
 91              MARACUYA  ,
 'FRESA':      BP Departamento  Hombres  Mujeres  Total Víctimas  \
 77  348    ANTIOQUIA        0       30              12

     Valor total cofinanciación ADR  Valor Contrapartida  Hectáreas  Vigencia  \
 77                       496060000             78225000          5      2017

    CADENA_PRODUCTIVA_ADR
 77                 FRESA  ,
 'COCO':      BP     Departamento  Hombres  Mujeres  Total Víctimas  \

In [92]:
# upsample minority
categories_oversampling = categories[1:18]

In [93]:
categories_oversampling

array(['CAFE', 'CAUCHO', 'TOMATE', 'MANGO', 'CACAO', 'ÑAME', 'MORA',
       'AGUACATE', 'GRANADILLA', 'TANGELO', 'PERA', 'MAIZ', 'PAPA',
       'FRIJOL', 'MARACUYA', 'FRESA', 'COCO'], dtype=object)

In [95]:
upsample = {}
for category in categories_oversampling:
    upsample.update({str(category)+"_upsample": resample(classes[category],replace = True, n_samples =31)})

In [102]:
# combine majority and upsampled minority
upsample_df = classes["PLATANO"]
for category in categories_oversampling:
    upsample_df = pd.concat([upsample_df, upsample[str(category)+"_upsample"]])

In [105]:
len(upsample_df)

558

In [108]:
# check new class counts
upsample_df.CADENA_PRODUCTIVA_ADR.value_counts()

MARACUYA      31
CAFE          31
MAIZ          31
FRESA         31
CACAO         31
ÑAME          31
PERA          31
GRANADILLA    31
FRIJOL        31
TOMATE        31
COCO          31
PAPA          31
PLATANO       31
TANGELO       31
CAUCHO        31
MORA          31
MANGO         31
AGUACATE      31
Name: CADENA_PRODUCTIVA_ADR, dtype: int64