# Database

## Creation database

In [1]:
# User to execute: postgres
# NOTE: DON'T EXECUTE AGAIN

#%%sql
#CREATE DATABASE adr_db
#   ENCODING = 'UTF8'
#   TABLESPACE = pg_default
#   LC_COLLATE = 'Spanish_Colombia.1252'
#   LC_CTYPE = 'Spanish_Colombia.1252';
#CREATE USER adr_user with login encrypted password '1234';
#grant all privileges on database adr_db to adr_user;

## Conection to database

In [1]:
%load_ext sql
%sql postgresql://adr_user:1234@ds4a-demo-instance.cct4rseci702.eu-west-1.rds.amazonaws.com/adr_db

In [5]:
%%sql
CREATE TABLE AP_SABANAGENERAL (
AP_Numero_BP   SMALLINT  PRIMARY KEY,
AP_Porcentaje_Avance   FLOAT,
AP_Beneficiarios_Definitivos   SMALLINT,
AP_Cant_Afrocolombiano   SMALLINT,
AP_Cant_Campesinos   SMALLINT,
AP_Cant_Mujeres   SMALLINT,
AP_Cant_Indigenas   SMALLINT,
AP_Cant_Hombre   SMALLINT,
AP_Cant_MujerRural   SMALLINT,
AP_Raizal   SMALLINT,
AP_Cant_Victimas   SMALLINT,
AP_Sector_Productivo   VARCHAR(255),
AP_ID_ADR   VARCHAR(6),
AP_CADENA_PRODUCTIVA_ADR   VARCHAR(60),
AP_Nombre_Proyecto   VARCHAR(600),
AP_Fecha_Resolucion   DATE,
AP_Departamento   VARCHAR(60)
);

CREATE TABLE ap_predios (
AP_Numero_BP   SMALLINT,
AP_ID_ADR   VARCHAR(6),
AP_CADENA_PRODUCTIVA_ADR   VARCHAR(60),
AP_Id_Predio   SMALLINT,
AP_Departamento   VARCHAR(60),
AP_Municipio   VARCHAR(60),
AP_Longitud_Predio_12   DECIMAL(18,15),
AP_Latitud_Predio_13   DECIMAL(18,15),
AP_Longitud_Predio_13   DECIMAL(18,15),
AP_Latitud_Predio_14   DECIMAL(18,15),
AP_Longitud_Predio_14   DECIMAL(18,15),
AP_Latitud_Predio_15   DECIMAL(18,15),
AP_Latitud_Predio_16   DECIMAL(18,15),
AP_Latitud_Predio_17   DECIMAL(18,15),
AP_Latitud_Predio_18   DECIMAL(18,15),
AP_Latitud_Predio_19   DECIMAL(18,15),
AP_Latitud_Predio_20   DECIMAL(18,15),
AP_Latitud_Predio_21   DECIMAL(18,15),
AP_Latitud_Predio_22   DECIMAL(18,15),
AP_Latitud_Predio_23   DECIMAL(18,15),
AP_Latitud_Predio_24   DECIMAL(18,15),
AP_Latitud_Predio_25   DECIMAL(18,15)
);

CREATE TABLE ap_activos (
AP_Numero_BP   SMALLINT,
AP_ID_ADR   VARCHAR(6),
AP_CADENA_PRODUCTIVA_ADR   VARCHAR(60),
AP_Horizonte   FLOAT,
AP_Activo_Productivo   VARCHAR(255),
AP_cantidad   FLOAT,
AP_Departamento   VARCHAR(60)
);

CREATE TABLE ds_asistencia_tecnica (
Id_Usuario   SMALLINT,
Sexo   VARCHAR(1),
Tipo_Poblacional   VARCHAR(60),
Discapacidad   VARCHAR(2),
Departamento   VARCHAR(60),
Municipio   VARCHAR(10),
Vereda   VARCHAR(255),
Predio   VARCHAR(255),
Cadena_Productiva   VARCHAR(255),
C1A1   SMALLINT,
C2A1   SMALLINT,
C3A1   SMALLINT,
C4A1   SMALLINT,
C5A1   SMALLINT,
C6A1   SMALLINT,
C7A1   SMALLINT,
C8A1   SMALLINT,
C9A1   SMALLINT,
C10A1   SMALLINT,
NA1   SMALLINT,
C1A2   SMALLINT,
C2A2   SMALLINT,
C3A2   SMALLINT,
C4A2   SMALLINT,
C5A2   SMALLINT,
C6A2   SMALLINT,
C7A2   SMALLINT,
NA2   SMALLINT,
C1A3   SMALLINT,
C2A3   SMALLINT,
C3A3   SMALLINT,
C4A3   SMALLINT,
C5A3   SMALLINT,
NA3   SMALLINT,
C1A4   SMALLINT,
C2A4   SMALLINT,
C3A4   SMALLINT,
C4A4   SMALLINT,
NA4   SMALLINT,
C1A5   SMALLINT,
C2A5   SMALLINT,
C3A5   SMALLINT,
C4A5   SMALLINT,
NA5   SMALLINT,
CLAS_GRAL   SMALLINT,
CADENA_PRODUCTIVA_ADR   VARCHAR(60),
ID_ADR   VARCHAR(6),
Tipo_proyecto   VARCHAR(60)
);   
   
CREATE TABLE eva_cultivos (
COD_DEP   SMALLINT,
DEPARTAMENTO   VARCHAR(60),
COD_MUN   INTEGER,
MUNICIPIO   VARCHAR(60),
GRUP_CULTIVO   VARCHAR(60),
SUBGRUP_CULTIVO   VARCHAR(60),
CULTIVO   VARCHAR(60),
DESAGREGACION_SIST_PRODUCTIVO   VARCHAR(60),
YEAR   VARCHAR(4),
PERIODO   VARCHAR(5),
AREA_SEMBR   FLOAT,
AREA_COSECH   FLOAT,
PRODUCCION   FLOAT,
RENDIMIENTO   FLOAT,
ESTADO_PRODUCCION   VARCHAR(60),
NOMBRE_CIENTI   VARCHAR(60),
CICLO_CULTIVO   VARCHAR(20),
CADENA_PRODUCTIVA_ADR   VARCHAR(60),
NIVEL   SMALLINT,
ID_ADR   VARCHAR(6)
);   
   
CREATE TABLE adt_adecuaciontierras (   
Numero_BP   SMALLINT,
Departamento   VARCHAR(60),
Municipio   VARCHAR(60),
Vereda   VARCHAR(1000),
Predio   VARCHAR(60),
Organizacion   VARCHAR(60),
Id_Distrito   SMALLINT,
Nombre_Distrito   VARCHAR(1000),
Escala_Distrito   VARCHAR(60),
Tipo_Distrito   VARCHAR(60),
Distrito_Operativo   SMALLINT,
Area_Bruta_HA   FLOAT,
Area_Neta_Inicial_HA   FLOAT,
Familias   SMALLINT,
Principales_Cultivos   VARCHAR(1000),
Condición_Juridica   VARCHAR(60),
Propiedad_Distrito   VARCHAR(60),
Estado_Propiedad   VARCHAR(60),
Recursos_Construccion   VARCHAR(60),
Administrador_Distrito   VARCHAR(60),
Nombre_Fuente_Hidrica   VARCHAR(255),
Subzona_Hidrica   VARCHAR(60),
Corporacion_Autonoma_Regional   VARCHAR(60),
Concesión_Aguas   SMALLINT,
Numer_Consecion   VARCHAR(60),
Caudal_Consecion   FLOAT,
Fecha_Consecion   DATE,
Vigencia_Consecion   DATE,
Observaciones   TEXT
);
   
   
CREATE TABLE pidar (   
BP   SMALLINT,
No_VP   SMALLINT,
Nombre_Proyecto   TEXT,
Departamento   VARCHAR(60),
Municipio   VARCHAR(255),
Total_beneficiarios   SMALLINT,
Hombres   SMALLINT,
Mujeres   SMALLINT,
Total_Victimas   SMALLINT,
Valor_cofinanciado_ADR   FLOAT,
Valor_encargo_fiduciario   FLOAT,
Valor_total_cofinanciación_ADR   FLOAT,
Valor_Contrapartida   FLOAT,
Valor_total_proyecto   FLOAT,
Hectareas   FLOAT,
Resolucion   SMALLINT,
Fecha_resolucion   TIMESTAMP,
Vigencia   VARCHAR(4),
Lineamiento_consejo_directivo   VARCHAR(60),
AP_ID_ADR   VARCHAR(6),
AP_CADENA_PRODUCTIVA_ADR   VARCHAR(60)
);

 * postgresql://adr_user:***@ds4a-demo-instance.cct4rseci702.eu-west-1.rds.amazonaws.com/adr_db
Done.
Done.
Done.
Done.
Done.
Done.
Done.

[]

## Load data

```sql
-- Execute from terminal using plsql command located in "project" folder.  Data located in "Datasets" folder.
-- Standardize decimal (.) And field separator (;)
--  File saved as UTF8
-- Change decimal separator to ".":
    -- Excel Microsoft Office Button  / Excel Options / Advanced tab / Editing options / clear the Use system separators check box / Type Decimal separator and Thousands separator
-- Load files ending with "...2.csv" (decimal separator "." and field separator ";" )

SET datestyle = 'ISO,DMY';
SET CLIENT_ENCODING TO 'UTF8';
\copy ap_sabanageneral FROM '../Datasets/AP_SABANAGENERAL2.csv' with (format CSV, header true, delimiter ';', encoding 'utf8')
\copy ap_activos FROM '../Datasets/AP_ACTIVOS2.csv' with (format CSV, header true, delimiter ';', encoding 'utf8')
\copy ap_predios FROM '../Datasets/AP_PREDIOS2.csv' with (format CSV, header true, delimiter ';', encoding 'utf8')
\copy ds_asistencia_tecnica FROM '../Datasets/DS_Asistencia_Tecnica2.csv' with (format CSV, header true, delimiter ';', encoding 'utf8')
\copy eva_cultivos FROM '../Datasets/EVA_cultivos_modificado2.csv' with (format CSV, header true, delimiter ';', encoding 'utf8')
\copy adt_adecuaciontierras FROM '../Datasets/ADT_adecuaciontierras2.csv' with (format CSV, header true, delimiter ';', encoding 'utf8')
\copy pidar FROM '../Datasets/pidar2.csv' with (format CSV, header true, delimiter ';', encoding 'utf8')

```

In [5]:
%%sql
SELECT * FROM pidar limit 5;

 * postgresql://adr_user:***@ds4a-demo-instance.cct4rseci702.eu-west-1.rds.amazonaws.com/adr_db
5 rows affected.

[(6, 6, 'Mejorar las capacidades técnicas de adecuación, siembra y sostenimiento de plátano para la construcción de paz, beneficiando 35 familias en el municipio de Carmen del Darién - Chocó', 'CHOCO', 'CARMEN DEL DARIÉN', 35, 30, 5, 0, 250000000.0, None, 250000000.0, 513500000.0, 763500000.0, 100.0, 1219, None, '2017', None, '01', 'AGRICOLA'),
 (17, 17, 'Fortalecer la capacidad productiva y manejo de poscosecha mediante el establecimiento de 20 ha variedad resistente a roya, sostenimiento de 20 has de ... (81 characters truncated) ... otación de dos equipos de laboratorio para la Asociación de Caficultores de la Macarena y Sumapaz para el año 2017 en el municipio de Mesetas - Meta.', 'META', 'MESETAS', 40, 31, 9, 0, 500000000.0, None, 500000000.0, 106600000.0, 606600000.0, 40.0, 1250, None, '2017', None, '01', 'AGRICOLA'),
 (20, 20, 'Fortalecer la productividad y competitividad de 46 cacaoteros de las asociaciones ASOCADELCAT, ASOCOMMULCAT y ASOPROCAP, del muncipio de Tibú - departamento de Norte de Santander', 'NORTE DE SANTANDER', 'TIBÚ', 46, 31, 15, 21, 252785478.0, None, 252785478.0, 351466000.0, 604251478.0, 92.0, 1453, None, '2017', None, '01', 'AGRICOLA'),
 (23, 23, 'Fortalecer la cadena productiva de café y plátano, a través del suministro de insumos y asistencia técnica en la vereda Llano Grande de Chimiadó del municipio de Dabeiba, Antioquia', 'ANTIOQUIA', 'DABEIBA', 25, 20, 5, 23, 401373250.0, None, 401373250.0, 355140000.0, 756513250.0, 69.0, 1351, None, '2017', None, '01', 'AGRICOLA'),
 (25, 25, 'Fortalecimiento de la productividad del cultivo de caucho con la implementación de tecnologías a partir de la dotación de maquinaria e insumos agrícolas en las veredas Las Delicias, Aguazul, Buenos Aires, Altamira, Santa Teresa, Los Medios y El Billar del municipio de la Macarena - Meta', 'META', 'LA MACARENA', 28, 16, 12, 10, 255000000.0, None, 255000000.0, 41570000.0, 296570000.0, 93.0, 1401, None, '2017', None, '01', 'AGRICOLA')]